### ISSUE TITLE
Plot_Fig8.py still fails on both Linux and macOS

### ISSUE THREAD

**Issue by meling** [KaiqiangYu/SIGMOD24-ARI#3]
```console
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
% python3 Plot_Fig8d.py
Traceback (most recent call last):
  File "/home/ansatt/meling/sigmod-ari-2024/paper49/SIGMOD24-ARI/Exp-Rep/Plot_Fig8d.py", line 53, in <module>
    rects = ax.bar(x - (group-2*i-1)*width/2, y[i], width, label=legend[i],color=colors[i],edgecolor="k")
  File "/home/ansatt/meling/.local/lib/python3.10/site-packages/matplotlib/__init__.py", line 1476, in inner
    return func(
  File "/home/ansatt/meling/.local/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 2520, in bar
    x, height, width, y, linewidth, hatch = np.broadcast_arrays(
  File "/home/ansatt/meling/.local/lib/python3.10/site-packages/numpy/lib/_stride_tricks_impl.py", line 558, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/home/ansatt/meling/.local/lib/python3.10/site-packages/numpy/lib/_stride_tricks_impl.py", line 433, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (5,) and arg 1 with shape (10,).
```
On macOS:
```console
% python Plot_Fig8d.py 
/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/SIGMOD24-ARI/Exp-Rep/Plot_Fig8d.py:36: SyntaxWarning: invalid escape sequence '\g'
  labels1 = ['$\gamma$=0.94', '$\gamma$=0.92', '$\gamma$=0.90', '$\gamma$=0.88', '$\gamma$=0.86']
/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/SIGMOD24-ARI/Exp-Rep/Plot_Fig8d.py:36: SyntaxWarning: invalid escape sequence '\g'
  labels1 = ['$\gamma$=0.94', '$\gamma$=0.92', '$\gamma$=0.90', '$\gamma$=0.88', '$\gamma$=0.86']
/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/SIGMOD24-ARI/Exp-Rep/Plot_Fig8d.py:36: SyntaxWarning: invalid escape sequence '\g'
  labels1 = ['$\gamma$=0.94', '$\gamma$=0.92', '$\gamma$=0.90', '$\gamma$=0.88', '$\gamma$=0.86']
/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/SIGMOD24-ARI/Exp-Rep/Plot_Fig8d.py:36: SyntaxWarning: invalid escape sequence '\g'
  labels1 = ['$\gamma$=0.94', '$\gamma$=0.92', '$\gamma$=0.90', '$\gamma$=0.88', '$\gamma$=0.86']
/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/SIGMOD24-ARI/Exp-Rep/Plot_Fig8d.py:36: SyntaxWarning: invalid escape sequence '\g'
  labels1 = ['$\gamma$=0.94', '$\gamma$=0.92', '$\gamma$=0.90', '$\gamma$=0.88', '$\gamma$=0.86']
Traceback (most recent call last):
  File "/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/SIGMOD24-ARI/Exp-Rep/Plot_Fig8d.py", line 53, in <module>
    rects = ax.bar(x - (group-2*i-1)*width/2, y[i], width, label=legend[i],color=colors[i],edgecolor="k")
  File "/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/ARI-Package/Exp-Rep/plotenv/lib/python3.13/site-packages/matplotlib/__init__.py", line 1473, in inner
    return func(
        ax,
        *map(sanitize_sequence, args),
        **{k: sanitize_sequence(v) for k, v in kwargs.items()})
  File "/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/ARI-Package/Exp-Rep/plotenv/lib/python3.13/site-packages/matplotlib/axes/_axes.py", line 2520, in bar
    x, height, width, y, linewidth, hatch = np.broadcast_arrays(
                                            ~~~~~~~~~~~~~~~~~~~^
        # Make args iterable too.
        ^^^^^^^^^^^^^^^^^^^^^^^^^
        np.atleast_1d(x), height, width, y, linewidth, hatch)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/ARI-Package/Exp-Rep/plotenv/lib/python3.13/site-packages/numpy/lib/_stride_tricks_impl.py", line 558, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/Users/meling/Team-UIS Dropbox/Hein Meling/work/papers/reviews/sigmod-ari-2024/paper49/ARI-Package/Exp-Rep/plotenv/lib/python3.13/site-packages/numpy/lib/_stride_tricks_impl.py", line 433, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (5,) and arg 1 with shape (10,).
```

It looks like it is the same root cause, but I'm not familiar with Python details to debug this without spending time. Leaving it for you to fix if possible.

These are the input files for Fig8d (macOS):
```csv
110.377
130.751
160.917
152.67
191.83
```
```csv
8057.72
8990.7
9988.86
9965.39
11518.1
```

Just noticed that the second input file after the Linux run only had one sample, but copying over these files made no difference for the plot script.

**Comment by KaiqiangYu** [comment]
Thanks for your checking. The issue is fixed now.

**Comment by meling** [comment]
Can confirm it has been fixed.
